"""added index to blog model fields

Revision ID: e74c9e9b4d84
Revises: 79befb39e85d
Create Date: 2024-07-25 17:47:05.878080

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e74c9e9b4d84"
down_revision: Union[str, None] = "79befb39e85d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("blogs_title_key", "blogs", type_="unique")
    op.create_index(op.f("ix_blogs_created_at"), "blogs", ["created_at"], unique=False)
    op.create_index(op.f("ix_blogs_is_deleted"), "blogs", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_blogs_title"), "blogs", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blogs_title"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_is_deleted"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_created_at"), table_name="blogs")
    op.create_unique_constraint("blogs_title_key", "blogs", ["title"])
    # ### end Alembic commands ###
